-- Phase 503/504: WAITING_FOR_PATIENT_RESCHEDULE + default CONFIRMED

ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'WAITING_FOR_PATIENT_RESCHEDULE';

ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'CONFIRMED'::"AppointmentStatus";
